jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'    

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
    
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
