// <auto-generated />

using System;
using System.Runtime.InteropServices;

namespace ManagedCrunch
{
    public unsafe static class CrunchPInvoke
    {
        const string XamarinIOSObjectClassName = "Foundation.NSObject, Xamarin.iOS";

        public static readonly Delegates.crn_get_width crn_get_width;
        public static readonly Delegates.crn_get_height crn_get_height;
        public static readonly Delegates.crn_get_levels crn_get_levels;
        public static readonly Delegates.crn_get_dxt_format crn_get_dxt_format;
        public static readonly Delegates.crn_get_uncompressed_size crn_get_uncompressed_size;
        public static readonly Delegates.crn_decompress crn_decompress;

        static CrunchPInvoke()
        {
            var isXamarinIOS = Type.GetType(XamarinIOSObjectClassName) != null;
            if (isXamarinIOS)
            {
                crn_get_width = DllImportsXamarinIOS.crn_get_width;
                crn_get_height = DllImportsXamarinIOS.crn_get_height;
                crn_get_levels = DllImportsXamarinIOS.crn_get_levels;
                crn_get_dxt_format = DllImportsXamarinIOS.crn_get_dxt_format;
                crn_get_uncompressed_size = DllImportsXamarinIOS.crn_get_uncompressed_size;
                crn_decompress = DllImportsXamarinIOS.crn_decompress;
            }
            else
            {
                crn_get_width = DllImports.crn_get_width;
                crn_get_height = DllImports.crn_get_height;
                crn_get_levels = DllImports.crn_get_levels;
                crn_get_dxt_format = DllImports.crn_get_dxt_format;
                crn_get_uncompressed_size = DllImports.crn_get_uncompressed_size;
                crn_decompress = DllImports.crn_decompress;
            }
        }

        public static class Delegates
        {
            public delegate uint crn_get_width(byte* inBuffer, uint inBufferSize);
            public delegate uint crn_get_height(byte* inBuffer, uint inBufferSize);
            public delegate uint crn_get_levels(byte* inBuffer, uint inBufferSize);
            public delegate uint crn_get_dxt_format(byte* inBuffer, uint inBufferSize);
            public delegate uint crn_get_uncompressed_size(byte* inBuffer, uint inBufferSize);
            public delegate void crn_decompress(byte* inBuffer, uint inBufferSize, byte* outBuffer, uint outBufferSize);
        }

        public class DllImports
        {
            private const string DllName = "libcrunch";
			private const CallingConvention CallingConventionValue = CallingConvention.Cdecl;

            [DllImport(DllName, CallingConvention = CallingConventionValue)]
            public static extern uint crn_get_width(byte* inBuffer, uint inBufferSize);

            [DllImport(DllName, CallingConvention = CallingConventionValue)]
            public static extern uint crn_get_height(byte* inBuffer, uint inBufferSize);

            [DllImport(DllName, CallingConvention = CallingConventionValue)]
            public static extern uint crn_get_levels(byte* inBuffer, uint inBufferSize);

            [DllImport(DllName, CallingConvention = CallingConventionValue)]
            public static extern uint crn_get_dxt_format(byte* inBuffer, uint inBufferSize);

            [DllImport(DllName, CallingConvention = CallingConventionValue)]
            public static extern uint crn_get_uncompressed_size(byte* inBuffer, uint inBufferSize);

            [DllImport(DllName, CallingConvention = CallingConventionValue)]
            public static extern void crn_decompress(byte* inBuffer, uint inBufferSize, byte* outBuffer, uint outBufferSize);
        }

        public class DllImportsXamarinIOS
        {
            private const string DllName = "__Internal";

            [DllImport(DllName)]
            public static extern uint crn_get_width(byte* inBuffer, uint inBufferSize);

            [DllImport(DllName)]
            public static extern uint crn_get_height(byte* inBuffer, uint inBufferSize);

            [DllImport(DllName)]
            public static extern uint crn_get_levels(byte* inBuffer, uint inBufferSize);

            [DllImport(DllName)]
            public static extern uint crn_get_dxt_format(byte* inBuffer, uint inBufferSize);

            [DllImport(DllName)]
            public static extern uint crn_get_uncompressed_size(byte* inBuffer, uint inBufferSize);

            [DllImport(DllName)]
            public static extern void crn_decompress(byte* inBuffer, uint inBufferSize, byte* outBuffer, uint outBufferSize);
        }
    }
}
